# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def plugin_dev_pods
  test_pluginbase_source = nil
  test_plugincards_source = nil
  test_plugininox_source = nil
  test_plugingeofence_source = nil
  # test_pluginbase_source = { :git => 'https://github.com/moengage/iOS-PluginBase.git', :branch => '' }
  # test_pluginbase_source = { :path => '../../../iOS-PluginBase' }
  # test_plugincards_source = { :path => '../../../apple-plugin-cards' }
  # test_plugininox_source = { :path => '../../../apple-plugin-inbox' }
  # test_plugingeofence_source = { :path => '../../../apple-plugin-geofence' }
  pod 'MoEngagePluginBase', **test_pluginbase_source if test_pluginbase_source
  pod 'MoEngagePluginCards', **test_plugincards_source if test_plugincards_source
  pod 'MoEngagePluginInbox', **test_plugininox_source if test_plugininox_source
  pod 'MoEngagePluginGeofence', **test_plugingeofence_source if test_plugingeofence_source
end

def native_source
  test_source = nil
  # test_source = { :git => 'https://github.com/moengage/MoEngage-iPhone-SDK.git', :branch => '' }
  # test_source = { :path => '../../../MoEngage-iPhone-SDK' }
  return test_source
end

def native_dev_pods
  test_source = native_source
  return unless test_source
  pod 'MoEngage-iOS-SDK', **test_source
  pod 'MoEngageSecurity', **test_source
  pod 'MoEngageCore', **test_source
  pod 'MoEngageMessaging', **test_source
  pod 'MoEngageSDK', **test_source
  pod 'MoEngageTriggerEvaluator', **test_source
  pod 'MoEngageInApps', **test_source
  pod 'MoEngageCards', **test_source
  pod 'MoEngageInbox', **test_source
  pod 'MoEngageGeofence', **test_source
  pod 'MoEngageRichNotification', **test_source
  pod 'MoEngageRealTimeTrigger', **test_source
end

def extension_pods
  test_source = native_source
  if test_source
    pod 'MoEngageRichNotification', **test_source
  else
    pod 'MoEngageRichNotification'
  end
end

target 'SampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  native_dev_pods
  plugin_dev_pods

  target 'SampleAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'SampleSwiftApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'NotificationService' do
  extension_pods
end

target 'NotificationContent' do
  extension_pods
end

post_install do |installer|
  react_native_post_install(
    installer,
    "../node_modules/react-native",
    :mac_catalyst_enabled => false,
  )
  # Workaround for fmt consteval errors with Xcode 26.4+
  installer.pods_project.targets.each do |target|
    if target.name == 'fmt'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
  end
end
