name: Verify Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "development", "master" ]
jobs:
  verify-ios:
    runs-on: macos-15-xlarge
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v4
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: source
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup
        with:
          platform: ios
      - name: Setup dev environment
        uses: ./sdk-automation-scripts/actions/ios-action-setup
        env:
          SDK_BOT_ACCESS_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Verify iOS
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts iOS
  verify-react:
    runs-on: macos-15-xlarge
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v4
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: source
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup
        with:
          platform: hybrid
      - name: Verify React Framework
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts react-native
  verify-android-sample:
    runs-on: macos-15-xlarge
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v4
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: source
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      # Use -bin in CI for faster build
      - name: Use Gradle bin distribution for CI
        working-directory: source/SampleApp/android/gradle/wrapper
        run: |
          sed -i '' 's/-all\.zip/-bin.zip/' gradle-wrapper.properties
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup
        with:
          platform: android
      - name: Verify Android SampleApp
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts android-sample
  verify-android-expo:
    runs-on: macos-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v4
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: source
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      # Use -bin in CI for faster build
      - name: Use Gradle bin distribution for CI
        working-directory: source/SampleApp/android/gradle/wrapper
        run: |
          sed -i '' 's/-all\.zip/-bin.zip/' gradle-wrapper.properties
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup
        with:
          platform: android
      - name: Verify Android ExpoSampleApp
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts android-expo
