name: Verify Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "development", "master" ]
jobs:
  verify:
    runs-on: macos-latest
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      fail-fast: true
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v3
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup    
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          path: source
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Setup script
        working-directory: source
        run: |
          chmod +x .github/scripts/react-utils.main.kts
          chmod +x .github/scripts/verify-plugins.main.kts
      - name: Verify
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts
