name: Verify Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches: [ "development", "master" ]
jobs:
  verify-ios:
    runs-on: macos-15
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v3
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup
      - name: Setup dev environment
        uses: ./sdk-automation-scripts/actions/ios-action-setup
        env:
          SDK_BOT_ACCESS_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          path: source
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Setup script
        working-directory: source
        run: |
          chmod +x .github/scripts/react-utils.main.kts
          chmod +x .github/scripts/verify-plugins.main.kts
      - name: Verify iOS
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts iOS
  verify-react:
    runs-on: macos-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v3
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Setup script
        working-directory: source
        run: |
          chmod +x .github/scripts/react-utils.main.kts
          chmod +x .github/scripts/verify-plugins.main.kts
      - name: Verify React Framework
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts react-native
  verify-android:
    runs-on: macos-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout sdk automation scripts
        uses: actions/checkout@v3
        with:
          repository: moengage/sdk-automation-scripts
          path: sdk-automation-scripts
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Automation script setup
        uses: ./sdk-automation-scripts/actions/npm-repository-setup    
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          path: source
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}
      - name: Setup script
        working-directory: source
        run: |
          chmod +x .github/scripts/react-utils.main.kts
          chmod +x .github/scripts/verify-plugins.main.kts
      - name: Verify Android
        working-directory: source
        run: |
          kotlinc -script .github/scripts/verify-plugins.main.kts android
