// swift-tools-version: 6.0
// Swift Package Manager manifest for React Native's experimental SPM support
// (react-native >= 0.87, `npx react-native spm`). CocoaPods integration keeps
// using ReactNativeMoEngage.podspec — this file is only consumed by React
// Native's SPM autolinker.
//
// The autolinker references this package through a symlink at
// <app>/build/generated/autolinking/libs/ReactNativeMoEngage, so the relative
// `.package(path:)` entries below resolve against that location:
//   ../../../../xcframeworks -> <app>/build/xcframeworks   (ReactNative package)
//   ../../../ios             -> <app>/build/generated/ios  (React-GeneratedCode)
//
// The same symlink anchoring applies to the commented-out "For development"
// entries in `dependencies`: eight levels up from the symlink is the directory
// that holds sibling checkouts of the MoEngage native repos. That depth is a
// property of where the consuming app lives — it is correct for SpmSampleApp
// (<repo>/SpmSampleApp/ios), and has to be recounted for any other app.
//
// The product name must match the `spm.name` override declared in this
// package's react-native.config.js — that is how the autolinker learns to
// look it up as "ReactNativeMoEngage" rather than the name it would otherwise derive.

import PackageDescription

let package = Package(
    name: "ReactNativeMoEngage",
    // iOS only, and pinned at 15 — neither value is free to choose:
    //
    // * SwiftPM forbids a target declaring a floor below the products it
    //   consumes, and React Native's generated codegen package
    //   (ReactAppHeaders) declares .iOS(.v15). Lowering this to 13 to match the
    //   podspec fails the build outright with "The package product
    //   'ReactAppHeaders' requires minimum platform version 15.0 for the iOS
    //   platform, but this target supports 13.0". That file is regenerated by
    //   React Native, so it cannot be patched from here. SPM consumers are
    //   bound to iOS 15; CocoaPods consumers keep the podspec's iOS 13.
    //
    // * No tvOS: React.xcframework and ReactNativeHeaders.xcframework ship no
    //   tvOS slice (only hermes-engine and ReactNativeDependencies do), and
    //   this target includes those React headers, so it cannot build for tvOS.
    //   The react-native-tvos fork does not help — its scripts/spm is identical
    //   to upstream and pulls the same iOS-only React artifacts. Declaring
    //   .tvOS here would advertise support that cannot be built.
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "ReactNativeMoEngage",
            targets: ["ReactNativeMoEngage", "ReactNativeMoEngageSwift"]
        ),
    ],
    dependencies: [
        .package(name: "ReactNative", path: "../../../../xcframeworks"),
        .package(name: "React-GeneratedCode", path: "../../../ios"),
        .package(url: "https://github.com/moengage/iOS-PluginBase.git", exact: "7.00.0"),
        // For development against a local checkout, comment the line above
        // and uncomment this one:
        // .package(path: "../../../../../../../../iOS-PluginBase"),
        .package(url: "https://github.com/moengage/apple-sdk.git", exact: "11.00.0"),
        // For development against a local checkout, comment the line above
        // and uncomment this one:
        // .package(path: "../../../../../../../../apple-sdk"),
    ],
    targets: [
        .target(
            name: "ReactNativeMoEngage",
            dependencies: [
                .product(name: "ReactHeaders", package: "ReactNative"),
                .product(name: "ReactNativeHeaders", package: "ReactNative"),
                .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
                .product(name: "ReactAppHeaders", package: "React-GeneratedCode"),
                .product(name: "MoEngagePluginBase", package: "iOS-PluginBase"),
                .product(name: "MoEngageSDK", package: "apple-sdk"),
                .product(
                    name: "MoEngageRichNotification",
                    package: "apple-sdk",
                    condition: .when(platforms: [.iOS])
                ),
            ],
            path: "iOS/MoEReactBridge",
            // All headers are public, matching CocoaPods. The bridge headers keep
            // the ObjC++ only TurboModule spec import in their .mm instead, so
            // this module's Clang umbrella stays compilable from plain ObjC.
            publicHeadersPath: ".",
            // RCT_NEW_ARCH_ENABLED must be defined for BOTH the plain ObjC (.m)
            // and ObjC++ (.mm) sources: the bridge headers switch the class's
            // protocol conformance on it, so a mismatch across translation
            // units breaks the TurboModule. CocoaPods sets this on pod targets
            // under the New Architecture; SwiftPM does not, and without it
            // React Native 0.87 never dispatches to the module (legacy module
            // interop is disabled by default).
            cSettings: [
                .define("RCT_NEW_ARCH_ENABLED"),
            ],
            cxxSettings: [
                .define("RCT_NEW_ARCH_ENABLED"),
                // Match the prebuilt React.framework's config-gated C++ ABI
                // (NDEBUG in Release changes Fabric's ShadowNode layout).
                .define("DEBUG", .when(configuration: .debug)),
                .define("NDEBUG", .when(configuration: .release)),
            ],
            linkerSettings: [
                .linkedFramework("UIKit"),
                .linkedFramework("Foundation"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("UserNotifications", .when(platforms: [.iOS])),
            ]
        ),
        // SPM cannot compile Swift and Objective-C in a single target, so the
        // Swift integration shim lives in its own target. It is part of the
        // "ReactNativeMoEngage" library product above, so consumers still get
        // both by depending on the product.
        .target(
            name: "ReactNativeMoEngageSwift",
            dependencies: [
                "ReactNativeMoEngage",
                .product(name: "MoEngagePluginBase", package: "iOS-PluginBase"),
                .product(name: "MoEngageSDK", package: "apple-sdk"),
            ],
            path: "iOS/MoEReactSwift"
        ),
    ],
    cxxLanguageStandard: .cxx20
)
